print("Warren N. Malangis")
print("Cawit, Boac, Marinduque")
print("May 08, 2002")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("2C")
print("Watching anime")
print("Playing piano")
print("Watching movies")
print("Reading manga")
print("Gardening")